/* dock_plugin_uwu.vapi generated by valac 0.52.6, do not modify. */

[CCode (gir_namespace = "dock_plugin_uwu", gir_version = "0.1")]
namespace DockPlugin {
	[CCode (cheader_filename = "dock_plugin_uwu.h")]
	public static Gtk.Image image ();
	[CCode (cheader_filename = "dock_plugin_uwu.h")]
	public static string name ();
	[CCode (cheader_filename = "dock_plugin_uwu.h")]
	public static Gtk.Box popover_menu ();
}
