/* dock_plugin_uwu.h generated by valac 0.52.6, the Vala compiler, do not modify */

#ifndef __DOCK_PLUGIN_UWU_H__
#define __DOCK_PLUGIN_UWU_H__

#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

G_BEGIN_DECLS

GtkImage* dock_plugin_image (void);
GtkBox* dock_plugin_popover_menu (void);
gchar* dock_plugin_name (void);

G_END_DECLS

#endif
